name: Build a Project Go

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        type: string
        default: ${{ github.repository }}
      USERNAME:
        type: string
        default: ${{ github.actor }}
      NAME_DEPLOY:
        type: string
        default: ${{ github.repository }}
      OVERRIDE_GO_VERSION: # any way to inherit + other secret ?
        type: string
      OVERRIDE_GO_PRIVATE: # any way to inherit + other secret ?
        type: string
      DEPLOY:
        type: string
        default: deploy
      GET_LIB:
        type: string
      DO_CONF_GIT:
        type: boolean
        default: true
      DO_DEPENDENCIES:
        type: string
      DO_MOD_DOWNLOAD:
        type: boolean
        default: true
      DO_GENERATE:
        type: boolean
        default: true
      DO_GENERATE_SWAGGER_SERVER:
        type: string
      DO_GENERATE_CUSTOM_PATH:
        type: string
      DO_BUILD:
        type: boolean
        default: true
      DO_BUILD_CUSTOM_PATH:
        type: string
      DO_SONAR:
        type: boolean
        default: true      
      DO_TEST:
        type: boolean
        default: true
      DO_LINT:
        type: boolean
        default: true
      DO_BUILD_DOCKER:
        type: boolean
        default: true
      DO_DEPLOY:
        type: boolean
        default: true
      
    secrets:
      GOPRIVATE:
        required: true
      REGISTRY:
        required: true
      GIT_CONFIG_KEY:
        required: true
      GIT_CONFIG_VALUE:
        required: true
      GO_VERSION:
        required: true
      LIB_LINT:
        required: true
      CMD_LINT:
        required: true
      GH_PACKAGES:
        required: true
      KUBE_INT_CONFIG:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      K8S_CONTEXT:
        required: true

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  GH_ACCESS_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
  GOPRIVATE: ${{ inputs.OVERRIDE_GO_PRIVATE || secrets.GOPRIVATE }}
  GO_VERSION: ${{ inputs.OVERRIDE_GO_VERSION || secrets.GO_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}


      - name: Cache Go
        id: cache-go
        uses: actions/cache@v3
        env:
          cache-name: cache-go
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.cache-go }}-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.cache-go }}-
            ${{ runner.os }}-go-
            ${{ runner.os }}-

      - name: Config Git
        if: "${{ inputs.DO_CONF_GIT == true }}"
        run: git config --global ${{ secrets.GIT_CONFIG_KEY }} ${{ secrets.GIT_CONFIG_VALUE }}

      - name: Install dependencies
        if: "${{ inputs.DO_DEPENDENCIES != '' }}"
        run: go install ${{ inputs.DO_DEPENDENCIES }}

      - name: Go mod download
        if: "${{ inputs.DO_MOD_DOWNLOAD == true }}"
        run: 	go mod download

      - name: Get lib
        if: "${{ inputs.GET_LIB  != '' }}"
        run: 	go get ${{inputs.GET_LIB}}

      - name: Generate sources
        if: "${{ inputs.DO_GENERATE == true }}"
        run: go generate ./...

      - name: Generate swagger server
        if: "${{ inputs.DO_GENERATE_SWAGGER_SERVER != '' }}"
        run: swagger generate server ${{ inputs.DO_GENERATE_SWAGGER_SERVER }}

      - name: Generate sources custom path
        if: "${{ inputs.DO_GENERATE_CUSTOM_PATH != '' }}"
        run: go generate ${{ inputs.DO_GENERATE_CUSTOM_PATH }}

      - name: Go build
        if: "${{ inputs.DO_BUILD == true }}"
        run: 	go build .

      - name: Go build custom path
        if: "${{ inputs.DO_BUILD_CUSTOM_PATH != '' }}"
        run: 	go build ${{ inputs.DO_BUILD_CUSTOM_PATH }}

      - uses: sonarsource/sonarqube-scan-action@master
        if: "${{ inputs.DO_SONAR == true }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   if: "${{ inputs.DO_SONAR == true }}"
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Tests
        if: "${{ always() && inputs.DO_TEST == true }}"
        run: go test ./...

      # - name: Lint
      #   if: "${{ always() && inputs.DO_LINT == true }}"
      #   run: go install ${{secrets.LIB_LINT}}; ${{secrets.CMD_LINT}}

      - name: Log in to the Container registry
        if: "${{ github.event_name != 'pull_request' && inputs.DO_BUILD_DOCKER == true && always() }}"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ inputs.USERNAME }}
          password: ${{ secrets.GH_PACKAGES }}

      - name: Extract metadata (tags, labels) for Docker
        if: "${{ github.event_name != 'pull_request' && inputs.DO_BUILD_DOCKER == true && always() }}"
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.REGISTRY }}/${{ inputs.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        if: "${{ github.event_name != 'pull_request' && inputs.DO_BUILD_DOCKER == true && always() }}"
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: "${{ github.event_name != 'pull_request' && inputs.DO_BUILD_DOCKER == true && always() }}"
        uses: docker/setup-buildx-action@v2

      - name: Docker Push
        if: "${{ github.event_name != 'pull_request' && inputs.DO_BUILD_DOCKER == true && always() }}"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:

    if: "${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' && inputs.DO_DEPLOY == true }}"
    needs: build
    runs-on: ubuntu-latest

    env:
      MA_VARIABLE: ${{ shell.exec("echo ${{ inputs.IMAGE_NAME }} | cut -d "/" -f 2") }}

    steps:
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.22.11'

      - name: Configure Kubectl
        run: |
          echo ${{ secrets.KUBE_INT_CONFIG }} | base64 -d > kubeconfig
          echo ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' && inputs.DO_DEPLOY == true }}
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_INT_CONFIG }}

      - name: Deploy to ${{ secrets.K8S_CONTEXT }}
        run: |
          echo $MA_VARIABLE
# REPO_NAME=$(echo ${{ inputs.IMAGE_NAME }} | cut -d "/" -f 2)
# kubectl --kubeconfig=./kubeconfig \
#   --context=${{ secrets.K8S_CONTEXT }} \
#   patch ${{ inputs.DEPLOY }} $REPO_NAME-${{ inputs.DEPLOY }} -p '{"spec":{"template":{"metadata":{"labels":{"build_number":"${{ github.run_id }}"}}}}}'